[theme]
primaryColor = "#c81373"
backgroundColor = "#faf5f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
